### ISSUE TITLE
Loading pre-trained model throws error

### ISSUE THREAD

**Issue by karynaur** [researchmm/AOT-GAN-for-Inpainting#1]
After adding the downloaded pretrained model into `experiments/`, running `demo.py` throws 
```
IsADirectoryError: [Errno 21] Is a directory: 'experiments/'
```
![image](https://user-images.githubusercontent.com/25678782/113694042-e302ec80-96ec-11eb-8fbb-32b8e77b44c9.png)

**Comment by 1900zyh** [comment]
Hi @karynaur,

Thanks for your interest! 
For the issue, you need to download the pre-trained model and put it under the folder `experiments`. 
Then specify the path to the model by `--pre_train experiments/xxx/xxx.pt`. 

Thanks.

**Comment by karynaur** [comment]
Thank you for the reply @1900zyh !!
I tried the same and it seems to run but without any output
```py
!python demo.py --dir_image ../1.jpg --pre_train experiments/G0000000.pt --painter bbox --outputs /content/out.jpg
```
Like in here the cell runs successfully but i dont seem to find any image `out.jpg` in `/content/`

**Comment by karynaur** [comment]
Fixed it! Thanks!
This solved it:
```py
>>>python demo.py --dir_image ./images/ --pre_train ./experiments/places/G0000000.pt 
```
