### ISSUE TITLE
用celeba_256数据集从头训练为什么无法收敛？

### ISSUE THREAD

**Issue by Cynicarlos** [researchmm/AOT-GAN-for-Inpainting#12]
感谢作者的贡献！请问我用celeba_256从scratch开始训练，但每张图片对应一张固定的mask，且输入图含噪声，算loss时用的是clean的GT，batch_size调成16，iteration为1e6，为什么一直没有收敛呢？
最后的log如下：
mt:7.5s, dt:0.0s, L1:0.390, Style:0.700, Perceptual:0.389, advg:0.006, advd:0.000, : 100%|█████████▉| 999666/1000000 [139:05:29<04:09,  1.34it/s]

**Comment by 7423cg** [comment]
> 感谢作者的贡献！请问我用celeba_256从scratch开始训练，但每张图片对应一张固定的mask，且输入图含噪声，算loss时用的是clean的GT，batch_size调成16，iteration为1e6，为什么一直没有收敛呢？ 最后的log如下： mt:7.5s, dt:0.0s, L1:0.390, Style:0.700, Perceptual:0.389, advg:0.006, advd:0.000, : 100%|█████████▉| 999666/1000000 [139:05:29<04:09, 1.34it/s]
did you solved it?

**Comment by 7423cg** [comment]
> 感谢作者的贡献！请问我用celeba_256从scratch开始训练，但每张图片对应一张固定的mask，且输入图含噪声，算loss时用的是clean的GT，batch_size调成16，iteration为1e6，为什么一直没有收敛呢？ 最后的log如下： mt:7.5s, dt:0.0s, L1:0.390, Style:0.700, Perceptual:0.389, advg:0.006, advd:0.000, : 100%|█████████▉| 999666/1000000 [139:05:29<04:09, 1.34it/s]

did you solve it?
