### ISSUE TITLE
Unable to train

### ISSUE THREAD

**Issue by s8088899** [researchmm/AOT-GAN-for-Inpainting#19]
I can't use my own training set, I prepared some 512*512 images for training, but my progress bar keeps staying at 0,
like this:

[**] create folder ../experiments/aotgan_places2_pconv512
UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG19_Weights.IMAGENET1K_V1`. You can also use `weights=VGG19_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
  0%|                                                                                                                                                                                           | 0/1000000 [00:00<?, ?it/s]

**Comment by s8088899** [comment]
I have solved the problem, but the model gives an error when saving:
AttributeError: 'InpaintGenerator' object has no attribute 'module'

**Comment by bucaiLi** [comment]
我现在也是训练进度为0，你是怎怎么解决的这个问题？
